NumPy, which is the fundamental package for scientific computing in Python. NumPy consists of a robust data structure called multidimensional arrays. Pandas is another powerful Python library that provides a fast and easy-to-use data analysis platform.


## NumPy<br>
NumPy, which stands for ‘Numerical Python’, is a library meant for scientific calculations. The basic data structure of NumPy is an array. A NumPy array is a collection of values stored together, similar to a list. 

In [1]:
print("hello")

hello


unlike lists it can multiply each element from the array with 2 or any value

In [4]:
import numpy as np
np_height = np.array([74,75,72,72,71])
np_height * 2

array([148, 150, 144, 144, 142])

In [5]:
list_1 = [1,2,3]
list_2 = [4,5,6]
list_1 + list_2

[1, 2, 3, 4, 5, 6]

In [6]:
np_list1 = np.array([1,2,3])
np_list2 = np.array([4,5,6])
np_list1 + np_list2


array([5, 7, 9])

convert aray from inch to meter

In [10]:
heights = [71,72,73,72,77,77,76,75,78,76,72,71,75,73]
heights_in = np.array(heights)
heights_in.size #this will provide you the length of the array
heights_in.shape # this will provide you 1D or 2d array size, since there is no 2nd Dimension

(14,)

In [11]:
#Converting inch to mtr
heights_m = heights_in * 0.0254
heights_m

array([1.8034, 1.8288, 1.8542, 1.8288, 1.9558, 1.9558, 1.9304, 1.905 ,
       1.9812, 1.9304, 1.8288, 1.8034, 1.905 , 1.8542])

Sub Setting Array

In [12]:
# fetch first element of the array
heights_m[1]

1.8288

In [13]:
heights_m[0:5]

array([1.8034, 1.8288, 1.8542, 1.8288, 1.9558])

Conditional subsetting

In [15]:
# count the number of heights less than 1.9
heights_m < 1.9

array([ True,  True,  True,  True, False, False, False, False, False,
       False,  True,  True, False,  True])

In [17]:
less_height = heights_m [heights_m < 1.9] #this is subset of the array and then set condition which is caluclatiing the heights less than 1.9
less_height

array([1.8034, 1.8288, 1.8542, 1.8288, 1.8288, 1.8034, 1.8542])

NumPy Functions

In [18]:
max(heights_m)

1.9811999999999999

In [19]:
heights_m.min()

1.8034

In [20]:
heights_m.mean()

1.8832285714285715

In [26]:
array_1 = [1,2,3,5,4,6,7,8,5,3,2]
print(array_1[1: : 2])

[2, 5, 6, 8, 3]


From a given array, extract all the elements which are greater than 'm' and less than 'n'. Note: 'm' and 'n' are integer values provided as input.



Input format:

A list of integers on line one

Integer 'm' on line two

Integer 'n' on line three

In [43]:
import ast 
input_list=ast.literal_eval(input())
m=int(input())
n=int(input())

import numpy as np
array_1 = np.array(input_list)
final_array = array_1[ (array_1 > m) & (array_1 < n)]
print(final_array)

[9 7 9]


## Multidimensional Arrays <br>
A multidimensional array is an array of arrays. For example, a two-dimensional array would be an array with each element as a one-dimensional array. <br>
1-D array : [1, 2, 3, 4, 5]<br>
2-D array : [ [1, 2, 3, 4, 5], [6, 7, 8, 9, 10] ]

In [45]:
players = [(74, 180), (74, 215), (72, 210), (72, 210), (73, 188), (69, 176), (69, 209), (71, 200), (76, 231), (71, 180), (73, 188), (73, 180), (74, 185), (74, 160), (69, 180), (70, 185), (73, 189), (75, 185), (78, 219), (79, 230), (76, 205), (74, 230), (76, 195), (72, 180), (71, 192), (75, 225), (77, 203), (74, 195), (73, 182), (74, 188), (78, 200), (73, 180), (75, 200), (73, 200), (75, 245), (75, 240), (74, 215), (69, 185), (71, 175), (74, 199), (73, 200), (73, 215), (76, 200), (74, 205), (74, 206), (70, 186)]
import numpy as np
player_np = np.array(players)
len(player_np)

46

<h4 style = "color : Sky blue"> Example - 2 (Numpy Attributes)</h4>

##### Print the structure of the 2-D Array

In [48]:
player_np.shape #first element provides you the count of the array and second information provides you the number of information stored per set

(46, 2)

##### Print the dimensions of the array

In [49]:
player_np.ndim

2

In [50]:
player_np.dtype

dtype('int32')

fetch the first column from the array

In [51]:
player_np[:,0] #[row, column]

array([74, 74, 72, 72, 73, 69, 69, 71, 76, 71, 73, 73, 74, 74, 69, 70, 73,
       75, 78, 79, 76, 74, 76, 72, 71, 75, 77, 74, 73, 74, 78, 73, 75, 73,
       75, 75, 74, 69, 71, 74, 73, 73, 76, 74, 74, 70])

In [57]:
#fetch the height of 5th player from the array
player_np[4,0]

73

Description
Extract all the border rows and columns from a 2-D array.

Format:
Input: A 2-D Python list
Output: Four NumPy arrays - First column of the input array, first row of the input array, last column of the input array, last row of the input array respectively.

Example:
Input 1:
[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]

In [61]:
import ast
input_str = input()
input_list = ast.literal_eval(input_str)

import numpy as np
array_2d =np.array(input_list)
col_first = array_2d[:, 0]
row_first = array_2d[0, :]
col_last = array_2d[:, -1]
row_last = array_2d[-1, :]
print(col_first)
print(row_first)
print(col_last)
print(row_last)

[11 21 31]
[11 12 13 14]
[14 24 34]
[31 32 33 34]


## Operations on NumPy ArraysManipulate arrays<br>
Reshape arrays<br>
Stack arrays<br>
Perform operations on arrays<br>
Perform basic mathematical operations<br>
Power<br>
Absolute<br>
Trigonometric <br>
Exponential and logarithmic<br>
Apply built-in functions<br>
Apply your own functions<br>
Apply basic linear algebra operations<br>