NumPy, which is the fundamental package for scientific computing in Python. NumPy consists of a robust data structure called multidimensional arrays. Pandas is another powerful Python library that provides a fast and easy-to-use data analysis platform.


## NumPy<br>
NumPy, which stands for ‘Numerical Python’, is a library meant for scientific calculations. The basic data structure of NumPy is an array. A NumPy array is a collection of values stored together, similar to a list. 

In [1]:
print("hello")

hello


unlike lists it can multiply each element from the array with 2 or any value

In [4]:
import numpy as np
np_height = np.array([74,75,72,72,71])
np_height * 2

array([148, 150, 144, 144, 142])

In [5]:
list_1 = [1,2,3]
list_2 = [4,5,6]
list_1 + list_2

[1, 2, 3, 4, 5, 6]

In [6]:
np_list1 = np.array([1,2,3])
np_list2 = np.array([4,5,6])
np_list1 + np_list2


array([5, 7, 9])

convert aray from inch to meter

In [10]:
heights = [71,72,73,72,77,77,76,75,78,76,72,71,75,73]
heights_in = np.array(heights)
heights_in.size #this will provide you the length of the array
heights_in.shape # this will provide you 1D or 2d array size, since there is no 2nd Dimension

(14,)

In [11]:
#Converting inch to mtr
heights_m = heights_in * 0.0254
heights_m

array([1.8034, 1.8288, 1.8542, 1.8288, 1.9558, 1.9558, 1.9304, 1.905 ,
       1.9812, 1.9304, 1.8288, 1.8034, 1.905 , 1.8542])

Sub Setting Array

In [12]:
# fetch first element of the array
heights_m[1]

1.8288

In [13]:
heights_m[0:5]

array([1.8034, 1.8288, 1.8542, 1.8288, 1.9558])

Conditional subsetting

In [15]:
# count the number of heights less than 1.9
heights_m < 1.9

array([ True,  True,  True,  True, False, False, False, False, False,
       False,  True,  True, False,  True])

In [17]:
less_height = heights_m [heights_m < 1.9] #this is subset of the array and then set condition which is caluclatiing the heights less than 1.9
less_height

array([1.8034, 1.8288, 1.8542, 1.8288, 1.8288, 1.8034, 1.8542])

NumPy Functions

In [18]:
max(heights_m)

1.9811999999999999

In [19]:
heights_m.min()

1.8034

In [20]:
heights_m.mean()

1.8832285714285715

In [26]:
array_1 = [1,2,3,5,4,6,7,8,5,3,2]
print(array_1[1: : 2])

[2, 5, 6, 8, 3]


In [37]:
import ast 
input_list=ast.literal_eval(input())
m=int(input())
n=int(input())

import numpy as np
array_1 = np.array(input_list)
final_array = array_1 [ (array_1 > m) & (array_1 < n)]

print(final_array)

[ 1  5  9 12 15  7 12  9]
